# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    new_window_takes_over_fullscreen = 2
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    single_window_aspect_ratio = 1.0
}

# Group bar settings
group {
    groupbar {
        text_padding = 8
    }
}

# Cursor settings
cursor {
    no_hardware_cursors = true
    inactive_timeout = 3
}

# Window rules for floating windows
windowrule = size 80% 80%, floating:1
windowrule = center, floating:1
