import = ["~/.config/alacritty/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 3
padding.y = 3
decorations = "Buttonless"
opacity = 0.85
option_as_alt = "Both"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
