#!/usr/bin/env bash

echo "stowing dotfiles....."

for folder in $(echo "bin,p10k,tmux,nvim,zsh,alacritty,vscode,obsidian,pi,ghostty,kitty,claude-code,opencode,ssh,waybar,wezterm,yazi,zen-browser" | sed "s/,/ /g"); do
  echo "stowing $folder"
  stow -D $folder
  stow $folder
done
