# Terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Prefix
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Options
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
set -g extended-keys on
set -g extended-keys-format csi-u
setw -g mode-keys vi

# Pane splitting
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Pane zoom
bind -r m resize-pane -Z

# Pane resize (arrows)
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5
bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5

# Status position
set -g status-position top

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'fabioluciano/tmux-powerkit'

# Resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

# Continuum
set -g @continuum-restore 'on'

# Sessionx
set -g @sessionx-bind 's'
set -g @sessionx-x-path '~/dotfiles'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'
set -g @sessionx-bind-zo-new-window 'ctrl-y'

# Floax
set -g @floax-bind 'p'
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-change-path 'true'

# Powerkit - Status bar framework
set -g @powerkit_plugins "cpu,netspeed,battery,datetime"
set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "macchiato"
set -g @powerkit_separator_style "flame"
set -g @powerkit_status_order "session,plugins"
set -g @powerkit_status_interval "5"
set -g @powerkit_plugin_datetime_format "%I:%M %p"
set -g @powerkit_plugin_datetime_icon "󰃰 "
set -g @powerkit_plugin_netspeed_display "download"

# Initialize TPM
run '~/.config/tmux/plugins/tpm/tpm'
